// Code generated by goyacc -o yacc.go yacc.y. DO NOT EDIT.

//line yacc.y:2
package yacc_parseJson

import __yyfmt__ "fmt"

//line yacc.y:2

func setScannerData(yylex interface{}, data interface{}) {
	yylex.(*Scanner).data = data
}

//line yacc.y:10
type yySymType struct {
	yys   int
	empty struct{}
	b     bool
	s     string
	i     interface{}
	a     []interface{}
	m     map[string]interface{}
}

const COMMA = 57346
const COLON = 57347
const LS = 57348
const RS = 57349
const LC = 57350
const RC = 57351
const TRUE = 57352
const FALSE = 57353
const NULL = 57354
const STRING = 57355
const NUMBER = 57356

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"COMMA",
	"COLON",
	"LS",
	"RS",
	"LC",
	"RC",
	"TRUE",
	"FALSE",
	"NULL",
	"STRING",
	"NUMBER",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 39

var yyAct = [...]int{
	2, 16, 21, 15, 28, 12, 13, 14, 10, 11,
	27, 18, 31, 26, 16, 19, 15, 22, 12, 13,
	14, 10, 11, 25, 24, 1, 29, 20, 30, 23,
	9, 17, 32, 8, 3, 7, 4, 6, 5,
}

var yyPact = [...]int{
	8, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 2, -5, 20, -1000, 18,
	6, -1000, -1000, -1000, -9, 8, -1000, 8, 7, -1000,
	-1000, 8, -1000,
}

var yyPgo = [...]int{
	0, 38, 37, 0, 36, 35, 34, 33, 31, 30,
	27, 25,
}

var yyR1 = [...]int{
	0, 11, 3, 3, 3, 3, 3, 3, 3, 7,
	7, 8, 8, 9, 9, 10, 10, 6, 4, 1,
	2, 5,
}

var yyR2 = [...]int{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	2, 3, 5, 3, 2, 1, 3, 1, 1, 1,
	1, 1,
}

var yyChk = [...]int{
	-1000, -11, -3, -6, -4, -1, -2, -5, -7, -9,
	13, 14, 10, 11, 12, 8, 6, -8, 9, 13,
	-10, 7, -3, 9, 4, 5, 7, 4, 13, -3,
	-3, 5, -3,
}

var yyDef = [...]int{
	0, -2, 1, 2, 3, 4, 5, 6, 7, 8,
	17, 18, 19, 20, 21, 0, 0, 0, 10, 0,
	0, 14, 15, 9, 0, 0, 13, 0, 0, 11,
	16, 0, 12,
}

var yyTok1 = [...]int{
	1,
}

var yyTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14,
}

var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:39
		{
			setScannerData(yylex, yyDollar[1].i)
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:45
		{
			yyVAL.i = yyDollar[1].s
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:49
		{
			yyVAL.i = yyDollar[1].i
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:53
		{
			yyVAL.i = yyDollar[1].b
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:57
		{
			yyVAL.i = yyDollar[1].b
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:61
		{
			yyVAL.i = yyDollar[1].i
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:65
		{
			yyVAL.i = yyDollar[1].m
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:69
		{
			yyVAL.i = yyDollar[1].a
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:75
		{
			yyVAL.m = yyDollar[2].m
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:79
		{
			// no-op
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:85
		{
			yyVAL.m = map[string]interface{}{yyDollar[1].s: yyDollar[3].i}
		}
	case 12:
		yyDollar = yyS[yypt-5 : yypt+1]
//line yacc.y:89
		{
			yyVAL.m = yyDollar[1].m
			yyVAL.m[yyDollar[3].s] = yyDollar[5].i
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:96
		{
			yyVAL.a = yyDollar[2].a
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line yacc.y:100
		{
			// no-op
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:106
		{
			yyVAL.a = []interface{}{yyDollar[1].i}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line yacc.y:110
		{
			yyVAL.a = append(yyDollar[1].a, yyDollar[3].i)
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:116
		{
			yyVAL.s = yyDollar[1].s
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:122
		{
			yyVAL.i = yyDollar[1].i
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:128
		{
			yyVAL.b = true
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:134
		{
			yyVAL.b = false
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line yacc.y:140
		{
			yyVAL.i = nil
		}
	}
	goto yystack /* stack new state and value */
}
