// Code generated by goyacc - DO NOT EDIT.

package yacc_parseJson

import __yyfmt__ "fmt"

func setScannerData(yylex interface{}, data interface{}) {
	yylex.(*Scanner).data = data
}

type yySymType struct {
	yys   int
	empty struct{}
	b     bool
	s     string
	i     interface{}
	a     []interface{}
	m     map[string]interface{}
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57357
	yyEofCode = 57344
	COLON     = 57347
	COMMA     = 57346
	FALSE     = 57353
	LC        = 57350
	LS        = 57348
	NULL      = 57354
	NUMBER    = 57356
	RC        = 57351
	RS        = 57349
	STRING    = 57355
	TRUE      = 57352
	yyErrCode = 57345

	yyMaxDepth = 200
	yyTabOfs   = -20
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		57346: 0,  // COMMA (20x)
		57351: 1,  // RC (17x)
		57349: 2,  // RS (17x)
		57344: 3,  // $end (16x)
		57355: 4,  // STRING (7x)
		57358: 5,  // array (5x)
		57360: 6,  // false (5x)
		57353: 7,  // FALSE (5x)
		57350: 8,  // LC (5x)
		57348: 9,  // LS (5x)
		57362: 10, // null (5x)
		57354: 11, // NULL (5x)
		57363: 12, // number (5x)
		57356: 13, // NUMBER (5x)
		57364: 14, // object (5x)
		57366: 15, // str (5x)
		57352: 16, // TRUE (5x)
		57367: 17, // true (5x)
		57368: 18, // value (5x)
		57347: 19, // COLON (2x)
		57359: 20, // array_data (1x)
		57361: 21, // json (1x)
		57365: 22, // object_data (1x)
		57357: 23, // $default (0x)
		57345: 24, // error (0x)
	}

	yySymNames = []string{
		"COMMA",
		"RC",
		"RS",
		"$end",
		"STRING",
		"array",
		"false",
		"FALSE",
		"LC",
		"LS",
		"null",
		"NULL",
		"number",
		"NUMBER",
		"object",
		"str",
		"TRUE",
		"true",
		"value",
		"COLON",
		"array_data",
		"json",
		"object_data",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {21, 1},
		2:  {18, 1},
		3:  {18, 1},
		4:  {18, 1},
		5:  {18, 1},
		6:  {18, 1},
		7:  {18, 1},
		8:  {18, 1},
		9:  {14, 3},
		10: {22, 3},
		11: {22, 5},
		12: {5, 3},
		13: {20, 1},
		14: {20, 3},
		15: {15, 1},
		16: {12, 1},
		17: {17, 1},
		18: {6, 1},
		19: {10, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [31][]uint8{
		// 0
		{4: 32, 29, 26, 35, 30, 31, 27, 36, 24, 33, 28, 23, 34, 25, 22, 21: 21},
		{3: 20},
		{3: 19},
		{18, 18, 18, 18},
		{17, 17, 17, 17},
		// 5
		{16, 16, 16, 16},
		{15, 15, 15, 15},
		{14, 14, 14, 14},
		{13, 13, 13, 13},
		{12, 12, 12, 12},
		// 10
		{4: 43, 22: 42},
		{4: 32, 29, 26, 35, 30, 31, 27, 36, 24, 33, 28, 23, 34, 25, 38, 20: 37},
		{5, 5, 5, 5},
		{4, 4, 4, 4},
		{3, 3, 3, 3},
		// 15
		{2, 2, 2, 2},
		{1, 1, 1, 1},
		{40, 2: 39},
		{7, 2: 7},
		{8, 8, 8, 8},
		// 20
		{4: 32, 29, 26, 35, 30, 31, 27, 36, 24, 33, 28, 23, 34, 25, 41},
		{6, 2: 6},
		{47, 46},
		{19: 44},
		{4: 32, 29, 26, 35, 30, 31, 27, 36, 24, 33, 28, 23, 34, 25, 45},
		// 25
		{10, 10},
		{11, 11, 11, 11},
		{4: 48},
		{19: 49},
		{4: 32, 29, 26, 35, 30, 31, 27, 36, 24, 33, 28, 23, 34, 25, 50},
		// 30
		{9, 9},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 24

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			setScannerData(yylex, yyS[yypt-0].i)
		}
	case 2:
		{
			yyVAL.i = yyS[yypt-0].s
		}
	case 3:
		{
			yyVAL.i = yyS[yypt-0].i
		}
	case 4:
		{
			yyVAL.i = yyS[yypt-0].b
		}
	case 5:
		{
			yyVAL.i = yyS[yypt-0].b
		}
	case 6:
		{
			yyVAL.i = yyS[yypt-0].i
		}
	case 7:
		{
			yyVAL.i = yyS[yypt-0].m
		}
	case 8:
		{
			yyVAL.i = yyS[yypt-0].a
		}
	case 9:
		{
			yyVAL.m = yyS[yypt-1].m
		}
	case 10:
		{
			yyVAL.m = map[string]interface{}{yyS[yypt-2].s: yyS[yypt-0].i}
		}
	case 11:
		{
			yyVAL.m = yyS[yypt-4].m
			yyVAL.m[yyS[yypt-2].s] = yyS[yypt-0].i
		}
	case 12:
		{
			yyVAL.a = yyS[yypt-1].a
		}
	case 13:
		{
			yyVAL.a = []interface{}{yyS[yypt-0].i}
		}
	case 14:
		{
			yyVAL.a = append(yyS[yypt-2].a, yyS[yypt-0].i)
		}
	case 15:
		{
			yyVAL.s = yyS[yypt-0].s
		}
	case 16:
		{
			yyVAL.i = yyS[yypt-0].i
		}
	case 17:
		{
			yyVAL.b = true
		}
	case 18:
		{
			yyVAL.b = false
		}
	case 19:
		{
			yyVAL.i = nil
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
